services:
  todoinfo-bot:
    image: ghcr.io/uchr/todoinfo:latest
    pull_policy: always
    env_file: .env
    volumes:
      - auth-cache:/root/.azure-cli-cache
      - data:/root/.todoinfo/data
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/app/todoinfo", "--help"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  auth-cache:
  data:
